### ISSUE TITLE
undefined reference to `irr::video::IdentityMaterial'

### ISSUE THREAD

**Issue by mckaygerhard** [MultiCraft/MultiCraft2#44]
##### Minetest version

```
i do not build minetest.. is multicraft! or what? licence problem?
```

##### OS / Hardware

Operating system: Debian
CPU: Xeon gold 4500 120 cores

GPU model: Radeon Xpress 400 (integrated)
OpenGL version: 3.0

##### Summary

Readme said `IRRLICHT_LIBRARY                - Path to libIrrlicht.a/libIrrlicht.so/libIrrlicht.dll.a/Irrlicht.lib` but that is incorrect.. must said `IRRLICHT_LIBRARY                - Path to libIrrlicht.a/libIrrlicht.so/libIrrlicht.dll.a/Irrlicht.lib including filename` so if only path are defined will raise this error: (i guess)

```
undefined reference to `irr::video::IdentityMaterial'
```

##### Steps to reproduce

configuring with `IRRLICHT_LIBRARY                - Path to libIrrlicht.a/libIrrlicht.so/libIrrlicht.dll.a/Irrlicht.lib` but that is incorrect.. must said `IRRLICHT_LIBRARY                - Path to libIrrlicht.a/libIrrlicht.so/libIrrlicht.dll.a/Irrlicht.lib including filename`

**Comment by MoNTE48** [comment]
Make sure you use Vanilla Irrlicht 1.8 and not IrrlichtMt or any other unofficial fork.

**Comment by mckaygerhard** [comment]
> Make sure you use Vanilla Irrlicht 1.8 and not IrrlichtMt or any other unofficial fork.

wrong.. the path must be defined in right way.. aftyer changed it builds.. as i mention and as seem you dont read, Readme for buil for play and more must be improved, i can hel with that

**Comment by ptrcnull** [comment]
> Make sure you use Vanilla Irrlicht 1.8 and not IrrlichtMt or any other unofficial fork.

@MoNTE48 I'm pretty sure he thinks "path to file" means path to a folder containing said file, for some reason...

It builds correctly with Irrlicht 1.8 installed and `-DIRRLICHT_LIBARY=/usr/lib/libIrrlicht.so.1.8.5`, so I think this can be closed.
